network:
  renderer: networkd
  version: 2
  ethernets:
      ens18:
        addresses:
          - 192.168.1.61/24
        nameservers:
          addresses: [1.1.1.1, 8.8.8.8]
        routes:
          - to : default
            via: 192.168.1.1
